---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pvc-training
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
      resources:
        requests:
          storage: 8Gi
      storageClassName: thin    